### ISSUE TITLE
Create Postman Documentation for the Backend

### ISSUE THREAD

**Issue by ZeldaMazzy** [ZeldaMazzy/codefi-capstone-24#21]
### Authentication Controller
- [x] Test the Register route. Verify it completes and you get back a token
- [x] Test the Login route. Verify it completes and you get back a token
### Account Controller
For the Account routes, you will need to get a token from the Register or Login route and attach it as a bearer token under the Authorization tab.
- [x] Test the AddAccount route. Verify you get back your newly created account. Do this a couple of times.
- [x] Test the EditAccount route on an existing account. Verify you get back the edited account.
- [x] Test the GetAllAccounts route. Verify you get back a list of Accounts.
- [x] Test the GetAccountById route. Verify you get back your Account.
- [x] Test the DeleteAccount route. Verify it deletes the account by checking the GetAccountById route afterwards.
### TransactionController
Much like the Account routes, here you will also need to attach a bearer token under the Authorization tab.
- [x] Test the AddTransaction route. Verify you get back your newly created transaction. You will need to attach an account and account id. Do this a couple of times. Below is a sample payload:
```
{
   "amount": 473,
   "account": [existing account id]
}
```
- [x] Test the EditTransaction route on an existing transaction. Verify you get back the edited transaction.
- [x] Test the GetAllTransactions route and pass an account ID in as a query string. Verify you get back a list of Transactions. Below is a sample query string:
`localhost:5000/api/v1/transactions?account=[some account id]`
- [x] Test the GetTransactionById route. Verify you get back your Transaction.
- [x] Test the DeleteTransaction route. Verify it deletes the transaction by checking the GetTransactionById route afterwards.

**Comment by mrkietzer** [comment]
https://app.getpostman.com/join-team?invite_code=2de27ff8dcbbaee1aded2cc368f8dc7d&target_code=da8f81bc691478838e60761af6e32d48
